//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bead_C5DLQT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hypeshop
    {
        public int Id { get; set; }
        public string Modell { get; set; }
        public Nullable<int> Vásárlási_ár { get; set; }
        public Nullable<int> Resell_Ár { get; set; }
        public string Méret { get; set; }
        public Nullable<int> Megjelenés_év_ { get; set; }
    }
}
